---
xe_latest:
  hostname: "ios-xe-mgmt-latest.cisco.com"
  groups:
    - ios

xe_stable:
  hostname: "ios-xe-mgmt.cisco.com"
  groups:
    - ios

xr_536:
  hostname: "sbx-iosxr-mgmt.cisco.com"
  groups:
    - iosxr
